# Generated by Django 4.1.7 on 2023-06-07 14:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bairro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('cidade', models.CharField(max_length=255)),
                ('uf', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Cidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('uf', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('documento', models.CharField(max_length=50)),
                ('telefone1', models.CharField(max_length=15)),
                ('telefone2', models.CharField(max_length=15)),
                ('CEP', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=50)),
                ('cidade', models.CharField(max_length=50)),
                ('bairro', models.CharField(max_length=50)),
                ('endereco', models.CharField(max_length=50)),
                ('numero_endereco', models.IntegerField()),
                ('complemento', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contas_Receber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pedido', models.IntegerField()),
                ('descricao', models.CharField(max_length=100)),
                ('data_vencimento', models.DateField(default=None, null=True)),
                ('data_pagamento', models.DateField(default=None, null=True)),
                ('tipo_pgto', models.CharField(default='PIX', max_length=50)),
                ('numero_parcela', models.IntegerField()),
                ('total_parcelas', models.IntegerField()),
                ('valor', models.FloatField()),
                ('status_conta', models.CharField(choices=[('Aberto', 'Aberto'), ('A Vencer', 'A Vencer'), ('Vencida', 'Vencida'), ('Pago', 'Pago')], default='Aberto', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Empresas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('razaosocial', models.CharField(max_length=100)),
                ('cnpj', models.CharField(max_length=15)),
                ('endereco', models.CharField(max_length=100)),
                ('telefone', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=50)),
                ('bairro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='connect.bairro')),
                ('cidade', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='connect.cidade')),
            ],
        ),
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigla', models.CharField(max_length=2)),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('descricao', models.CharField(max_length=50, null=True)),
                ('documento', models.CharField(max_length=50, unique=True)),
                ('nome_contato', models.CharField(max_length=50, null=True)),
                ('telefone', models.CharField(max_length=50, null=True)),
                ('email', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Itens_Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('pedido', models.IntegerField()),
                ('quantidade', models.IntegerField()),
                ('medida', models.CharField(default='0', max_length=100)),
                ('preco', models.FloatField()),
                ('desconto', models.FloatField(default='0.00', null=True)),
                ('total_item', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=120)),
                ('tamanho', models.CharField(max_length=10)),
                ('preco_base_comissao1', models.FloatField()),
                ('preco_base_comissao2', models.FloatField()),
                ('preco_base_comissao3', models.FloatField()),
                ('preco_base_comissao4', models.FloatField()),
                ('preco_base_comissao5', models.FloatField()),
                ('percentual_comissao1', models.IntegerField()),
                ('percentual_comissao3', models.IntegerField()),
                ('percentual_comissao5_interno', models.IntegerField()),
                ('percentual_comissao6_interno', models.IntegerField()),
                ('percentual_comissao7_interno', models.IntegerField()),
                ('percentual_comissao7_externo', models.IntegerField()),
                ('percentual_comissao10_externo', models.IntegerField()),
                ('percentual_comissao15_externo', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TipoPgto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=50)),
                ('nome_banco', models.CharField(max_length=50, null=True)),
                ('ag_banco', models.CharField(max_length=50, null=True)),
                ('cc_banco', models.CharField(max_length=50, null=True)),
                ('aceita_parcela', models.CharField(choices=[('NÃO', 'NÃO'), ('SIM', 'SIM')], default='NÃO', max_length=3)),
                ('numero_parcelas', models.IntegerField(default=1)),
                ('prazo_dias', models.CharField(default=30, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('datapedido', models.DateField()),
                ('prazo_entrega', models.DateField()),
                ('data_entrega_efetiva', models.DateField(default=None, null=True)),
                ('status', models.CharField(choices=[('Aberto', 'Aberto'), ('Produção', 'Produção'), ('PENDENTE_FINANCEIRO', 'PENDENTE_FINANCEIRO'), ('Liberado para Entrega', 'LIBERADO_ENTREGA'), ('Em Rota de Entrega', 'EM_ENTREGA'), ('Finalizado', 'FINALIZADO')], default='Aberto', max_length=50)),
                ('valorTotal', models.FloatField()),
                ('valorTotalParcial', models.FloatField()),
                ('frete_valor', models.FloatField(default=0.0, null=True)),
                ('descontototal', models.FloatField()),
                ('Vendedor', models.CharField(default=' ', max_length=200)),
                ('vendedor_comissao', models.FloatField()),
                ('Vendedor2', models.CharField(default=' ', max_length=200, null=True)),
                ('vendedor2_comissao', models.FloatField(null=True)),
                ('cep_entrega', models.CharField(max_length=10)),
                ('uf_entrega', models.CharField(max_length=2)),
                ('cidade_entrega', models.CharField(max_length=100)),
                ('bairro_entrega', models.CharField(max_length=100)),
                ('endereco_entrega', models.CharField(max_length=100)),
                ('numero_end_entrega', models.IntegerField()),
                ('complemento', models.CharField(max_length=100, null=True)),
                ('observacao', models.CharField(max_length=500, null=True)),
                ('cliente_pedido', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='connect.cliente')),
                ('empresa_pedido', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='connect.empresas')),
                ('frete_fornecedor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='connect.fornecedor')),
                ('itemPedido', models.ManyToManyField(related_name='itens_pedido', to='connect.produtos')),
                ('pgtotipo', models.ManyToManyField(related_name='tipos_pagamento', to='connect.tipopgto')),
            ],
        ),
        migrations.AddField(
            model_name='fornecedor',
            name='tipo_fornecedor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='connect.tipo_fornecedor'),
        ),
        migrations.AddField(
            model_name='empresas',
            name='uf',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='connect.estado'),
        ),
        migrations.CreateModel(
            name='Contas_Pagar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pedido', models.IntegerField(default=None, null=True)),
                ('descricao', models.CharField(max_length=100)),
                ('data_vencimento', models.DateField(null=True)),
                ('data_pagamento', models.DateField(default=None, null=True)),
                ('numero_parcela', models.IntegerField(default='1')),
                ('total_parcelas', models.IntegerField(default='1')),
                ('valor', models.FloatField()),
                ('fornecedor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='connect.fornecedor')),
                ('tipo_pgto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='connect.tipopgto')),
            ],
        ),
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('data_nascimento', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('cpf', models.CharField(max_length=11)),
                ('telefone', models.CharField(max_length=15)),
                ('funcao', models.CharField(choices=[('Gerente', 'Gerente'), ('Administrador', 'Administrador'), ('Vendedor Interno', 'Vendedor Interno'), ('Vendedor Externo', 'Vendedor Externo'), ('Producao', 'Produção'), ('Auxiliar', 'Auxiliar'), ('Logistica', 'Logística'), ('Financeiro', 'Financeiro'), ('Recepcionista', 'Recepcionista')], default=' ', max_length=30)),
                ('salario', models.FloatField()),
                ('endereco', models.CharField(max_length=50)),
                ('empresa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='connect.empresas')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
