# Generated by Django 4.1.7 on 2023-06-10 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contas_pagar',
            name='status',
            field=models.CharField(choices=[('Aberto', 'Aberto'), ('A Vencer', 'A Vencer'), ('Vencida', 'Vencida'), ('Pago', 'Pago')], default='Aberto', max_length=50),
        ),
    ]
