# Generated by Django 4.1.7 on 2023-06-10 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0002_contas_pagar_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='contas_pagar',
            name='outras_informacoes',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
