# Generated by Django 4.1.7 on 2023-06-11 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0003_contas_pagar_outras_informacoes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contas_pagar',
            name='outras_informacoes',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
