# Generated by Django 4.1.7 on 2023-06-13 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0004_alter_contas_pagar_outras_informacoes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_registro', models.IntegerField(unique=True)),
                ('data_entrega', models.DateField(default=None)),
                ('nome_recebedor', models.CharField(max_length=255, null=True)),
                ('documento_recebedor', models.CharField(max_length=30)),
                ('colaborador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='connect.colaborador')),
                ('pedido', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='connect.pedidos')),
            ],
        ),
    ]
