# Generated by Django 4.1.7 on 2023-06-13 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0005_registra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registra',
            name='data_entrega',
            field=models.DateTimeField(default=None),
        ),
    ]
