# Generated by Django 4.1.7 on 2023-06-13 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0006_alter_registra_data_entrega'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos',
            name='data_entrega_efetiva',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
