# Generated by Django 4.2.2 on 2023-06-15 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0007_alter_pedidos_data_entrega_efetiva'),
    ]

    operations = [
        migrations.AddField(
            model_name='bairro',
            name='zona',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
