# Generated by Django 4.2.2 on 2023-06-16 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0008_bairro_zona'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos',
            name='zona_entrega',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
