# Generated by Django 4.2.2 on 2023-06-18 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0009_pedidos_zona_entrega'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos',
            name='data_fim_producao',
            field=models.DateField(default=None, null=True),
        ),
        migrations.CreateModel(
            name='Producao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hora_conclusao', models.DateTimeField(default=None, null=True)),
                ('item_nome', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='connect.itens_pedido')),
                ('pedido', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='connect.pedidos')),
            ],
        ),
    ]
