# Generated by Django 4.2.2 on 2023-06-19 00:02

import connect.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0010_pedidos_data_fim_producao_producao'),
    ]

    operations = [
        migrations.CreateModel(
            name='Layout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to=connect.models.upload_layout)),
                ('numero_pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='connect.pedidos')),
            ],
        ),
    ]
