# Generated by Django 4.2.2 on 2023-06-19 03:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0011_layout'),
    ]

    operations = [
        migrations.AddField(
            model_name='layout',
            name='arquivo_nome',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='layout',
            name='numero_pedido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='connect.pedidos'),
        ),
    ]
