# Generated by Django 4.2.2 on 2023-06-19 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0012_layout_arquivo_nome_alter_layout_numero_pedido'),
    ]

    operations = [
        migrations.RenameField(
            model_name='layout',
            old_name='arquivo',
            new_name='arquivo_path',
        ),
    ]
