# Generated by Django 4.2.2 on 2023-06-19 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0013_rename_arquivo_layout_arquivo_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='total_pedidos',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='ultimopedido',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
