# Generated by Django 4.2.2 on 2023-06-20 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0015_pedidos_caminho_layout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos',
            name='zona_entrega',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
