# Generated by Django 4.2.2 on 2023-06-20 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0016_alter_pedidos_zona_entrega'),
    ]

    operations = [
        migrations.AddField(
            model_name='contas_pagar',
            name='documento_caminho',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
