# Generated by Django 4.2.2 on 2023-06-21 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0017_contas_pagar_documento_caminho'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtos',
            name='prazo_fabricacao',
            field=models.IntegerField(default=15),
        ),
        migrations.AddField(
            model_name='produtos',
            name='tipo_medida',
            field=models.CharField(default='m2', max_length=255),
        ),
    ]
