# Generated by Django 4.2.2 on 2023-06-21 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0018_produtos_prazo_fabricacao_produtos_tipo_medida'),
    ]

    operations = [
        migrations.AddField(
            model_name='itens_pedido',
            name='comprimento',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='itens_pedido',
            name='largura',
            field=models.FloatField(default=0.0, null=True),
        ),
    ]
