# Generated by Django 4.2.2 on 2023-06-21 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0019_itens_pedido_comprimento_itens_pedido_largura'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='dt_abertura',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='nome_contato',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
    ]
