# Generated by Django 4.2.2 on 2023-06-22 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0020_cliente_dt_abertura_cliente_nome_contato'),
    ]

    operations = [
        migrations.AddField(
            model_name='itens_pedido',
            name='valor_base',
            field=models.FloatField(default=1),
        ),
    ]
