# Generated by Django 4.2.2 on 2023-06-22 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0021_itens_pedido_valor_base'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produtos',
            old_name='percentual_comissao10_externo',
            new_name='percentual_comissao2',
        ),
        migrations.RenameField(
            model_name='produtos',
            old_name='percentual_comissao15_externo',
            new_name='percentual_comissao3_externo',
        ),
        migrations.RenameField(
            model_name='produtos',
            old_name='percentual_comissao3',
            new_name='percentual_comissao3_interno',
        ),
        migrations.RenameField(
            model_name='produtos',
            old_name='percentual_comissao6_interno',
            new_name='percentual_comissao4_externo',
        ),
        migrations.RenameField(
            model_name='produtos',
            old_name='percentual_comissao7_externo',
            new_name='percentual_comissao4_interno',
        ),
        migrations.RenameField(
            model_name='produtos',
            old_name='percentual_comissao7_interno',
            new_name='percentual_comissao5_externo',
        ),
    ]
