# Generated by Django 4.2.2 on 2023-06-23 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0022_rename_percentual_comissao10_externo_produtos_percentual_comissao2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos',
            name='pagamento_entrega',
            field=models.FloatField(default=0.0, null=True),
        ),
    ]
