# Generated by Django 4.2.2 on 2023-06-23 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0023_pedidos_pagamento_entrega'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contas_receber',
            name='status_conta',
            field=models.CharField(choices=[('Aberto', 'Aberto'), ('Pendente Faturamento', 'Pendente Faturamento'), ('A Vencer', 'A Vencer'), ('Vencida', 'Vencida'), ('Pago', 'Pago')], default='Aberto', max_length=50),
        ),
    ]
