# Generated by Django 4.2.2 on 2023-06-24 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0024_alter_contas_receber_status_conta'),
    ]

    operations = [
        migrations.AddField(
            model_name='itens_pedido',
            name='medida_final',
            field=models.FloatField(default=1),
        ),
    ]
