# Generated by Django 4.2.2 on 2023-06-24 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0025_itens_pedido_medida_final'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itens_pedido',
            name='medida',
            field=models.CharField(default='0', max_length=100, null=True),
        ),
    ]
