# Generated by Django 4.2.2 on 2023-06-25 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0026_alter_itens_pedido_medida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos',
            name='status',
            field=models.CharField(choices=[('Aberto', 'Aberto'), ('Produção', 'Produção'), ('PENDENTE FINANCEIRO', 'PENDENTE FINANCEIRO'), ('Liberado para Entrega', 'LIBERADO_ENTREGA'), ('Em Rota de Entrega', 'EM_ENTREGA'), ('Finalizado', 'FINALIZADO')], default='Aberto', max_length=50),
        ),
    ]
