# Generated by Django 4.2.2 on 2023-06-30 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0028_empresas_complemento_empresas_inscricao_estadual_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresas',
            name='endereco_numero',
            field=models.CharField(default=11, max_length=10),
        ),
    ]
