# Generated by Django 4.2.2 on 2023-06-30 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0029_empresas_endereco_numero'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresas',
            name='cep',
            field=models.CharField(default='24342702', max_length=11),
        ),
    ]
