# Generated by Django 4.2.2 on 2023-06-30 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0030_empresas_cep'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtos',
            name='ncm',
            field=models.IntegerField(default=84284000),
        ),
    ]
