# Generated by Django 4.2.2 on 2023-06-30 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0031_produtos_ncm'),
    ]

    operations = [
        migrations.AddField(
            model_name='itens_pedido',
            name='produto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produto_item', to='connect.produtos'),
        ),
    ]
