# Generated by Django 4.2.2 on 2023-06-30 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0032_itens_pedido_produto'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtos',
            name='codigo',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
