# Generated by Django 4.2.2 on 2023-06-30 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0033_produtos_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos',
            name='status',
            field=models.CharField(choices=[('Aberto', 'Aberto'), ('Produção', 'Produção'), ('PENDENTE FINANCEIRO', 'PENDENTE FINANCEIRO'), ('Liberado para Entrega', 'LIBERADO_ENTREGA'), ('Em Rota de Entrega', 'EM_ENTREGA'), ('Finalizado', 'FINALIZADO'), ('Entregue', 'Entregue'), ('Faturamento', 'Faturamento'), ('Pendente Logistica', 'Pendente Logistica'), ('Expedição', 'Expedição')], default='Aberto', max_length=50),
        ),
    ]
