# Generated by Django 4.2.2 on 2023-07-01 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0034_alter_pedidos_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos',
            name='pagamento_antecipado',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='pedidos',
            name='pagamento_faturado',
            field=models.FloatField(default=0.0, null=True),
        ),
    ]
