# Generated by Django 4.2.2 on 2023-07-01 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0035_pedidos_pagamento_antecipado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contas_receber',
            name='momento_pagamento',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
