# Generated by Django 4.2.2 on 2023-07-12 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0036_contas_receber_momento_pagamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='inscricao_estadual',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
    ]
