# Generated by Django 4.2.2 on 2023-07-14 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0038_fornecedor_bairro_fornecedor_cep_fornecedor_cidade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contas_pagar',
            name='comprovante_caminho',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contas_pagar',
            name='notafiscal',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
