# Generated by Django 4.2.2 on 2023-07-23 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0039_contas_pagar_comprovante_caminho_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contas_pagar',
            name='notafiscal_caminho',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
