# Generated by Django 4.2.2 on 2023-07-25 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0040_contas_pagar_notafiscal_caminho'),
    ]

    operations = [
        migrations.AddField(
            model_name='contas_receber',
            name='caminho_boleto',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
