# Generated by Django 4.2.2 on 2023-07-25 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0042_contas_receber_id_cobranca'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos',
            name='caminho_nfe',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pedidos',
            name='caminho_xml',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pedidos',
            name='numero_nfe',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='pedidos',
            name='referencia_nfe',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
