# Generated by Django 4.2.2 on 2023-07-25 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0043_pedidos_caminho_nfe_pedidos_caminho_xml_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos',
            name='numero_nfe',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
