# Generated by Django 4.2.2 on 2023-07-26 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0045_alter_pedidos_caminho_nfe_alter_pedidos_caminho_xml'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos',
            name='informacoes_adicionais',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
