# Generated by Django 4.2.2 on 2023-07-27 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0046_pedidos_informacoes_adicionais'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtos',
            name='medida_padrao',
            field=models.CharField(default='NAO', max_length=3, null=True),
        ),
    ]
