# Generated by Django 4.2.2 on 2023-07-27 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0047_produtos_medida_padrao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produtos',
            name='tamanho',
        ),
    ]
