# Generated by Django 4.2.2 on 2023-07-27 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0048_remove_produtos_tamanho'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtos',
            name='produto_adicional',
            field=models.CharField(default='NAO', max_length=3, null=True),
        ),
    ]
