# Generated by Django 4.2.2 on 2023-07-27 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0049_produtos_produto_adicional'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtos',
            name='tamanho_padrao',
            field=models.CharField(default='1', max_length=255, null=True),
        ),
    ]
