# Generated by Django 4.2.2 on 2023-07-27 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0050_produtos_tamanho_padrao'),
    ]

    operations = [
        migrations.AddField(
            model_name='itens_pedido',
            name='tipo',
            field=models.CharField(default='PADRAO', max_length=255, null=True),
        ),
    ]
