# Generated by Django 4.2.2 on 2023-07-28 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0052_alter_pedidos_informacoes_adicionais'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidos',
            name='informacoes_adicionais',
        ),
        migrations.AddField(
            model_name='pedidos',
            name='operacao_nota',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
