# Generated by Django 4.2.2 on 2023-07-29 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0054_pedidos_informacoes_adicionais'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos',
            name='frete_flag',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pedidos',
            name='frete_peso',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='status',
            field=models.CharField(choices=[('Aberto', 'Aberto'), ('Produção', 'Produção'), ('PENDENTE FINANCEIRO', 'PENDENTE FINANCEIRO'), ('Liberado para Entrega', 'LIBERADO_ENTREGA'), ('Em Rota de Entrega', 'EM_ENTREGA'), ('Finalizado', 'FINALIZADO'), ('Entregue', 'Entregue'), ('Financeiro', 'Financeiro'), ('Faturamento', 'Faturamento'), ('Pendente Logistica', 'Pendente Logistica'), ('Expedição', 'Expedição')], default='Aberto', max_length=50),
        ),
    ]
