# Generated by Django 4.2.2 on 2023-07-31 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0055_pedidos_frete_flag_pedidos_frete_peso_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos',
            name='flag_nfe',
            field=models.IntegerField(default=0),
        ),
    ]
