# Generated by Django 4.2.2 on 2023-07-31 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0056_pedidos_flag_nfe'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos',
            name='frete_volume',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
