# Generated by Django 4.2.2 on 2023-08-01 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0057_pedidos_frete_volume'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='id_clientecob',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contas_receber',
            name='status_cobranca',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
