# Generated by Django 4.2.2 on 2023-08-01 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0058_cliente_id_clientecob_contas_receber_status_cobranca'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos',
            name='justificativa_comissao',
            field=models.CharField(default=None, max_length=1000, null=True),
        ),
    ]
