# Generated by Django 4.2.2 on 2023-08-03 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0060_tipo_pedido'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produtos_Revenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=120)),
                ('preco_base_1', models.FloatField()),
                ('preco_base_2', models.FloatField()),
                ('preco_base_3', models.FloatField()),
                ('tipo_medida', models.CharField(default='m2', max_length=255)),
                ('prazo_fabricacao', models.IntegerField(default=15)),
                ('ncm', models.IntegerField(default=84284000)),
                ('codigo', models.IntegerField(default=None, null=True)),
                ('medida_padrao', models.CharField(default='NAO', max_length=3, null=True)),
                ('tamanho_padrao', models.CharField(default='1', max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Revenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('documento', models.CharField(max_length=50)),
                ('inscricao_estadual', models.CharField(default=None, max_length=10, null=True)),
                ('dt_abertura', models.DateField(default=None, null=True)),
                ('nome_contato', models.CharField(default=None, max_length=50, null=True)),
                ('telefone1', models.CharField(max_length=15)),
                ('telefone2', models.CharField(max_length=15)),
                ('CEP', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=50)),
                ('cidade', models.CharField(max_length=50)),
                ('bairro', models.CharField(max_length=50)),
                ('endereco', models.CharField(max_length=50)),
                ('numero_endereco', models.IntegerField()),
                ('complemento', models.CharField(max_length=100, null=True)),
                ('total_pedidos', models.IntegerField(default=None, null=True)),
                ('ultimopedido', models.IntegerField(default=None, null=True)),
                ('id_clientecob', models.CharField(default=None, max_length=100, null=True)),
                ('score', models.FloatField(default=5.0)),
            ],
        ),
        migrations.AddField(
            model_name='cliente',
            name='score',
            field=models.FloatField(default=5.0),
        ),
    ]
