# Generated by Django 4.2.2 on 2023-08-03 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0061_produtos_revenda_revenda_cliente_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtos_revenda',
            name='comissao',
            field=models.IntegerField(default=1),
        ),
    ]
