# Generated by Django 4.2.2 on 2023-08-03 02:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0062_produtos_revenda_comissao'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos',
            name='tipo_pedido',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='connect.tipo_pedido'),
        ),
    ]
