# Generated by Django 4.2.2 on 2023-08-03 03:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0064_cliente_tipo_cliente'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='revenda',
            name='CEP',
        ),
        migrations.RemoveField(
            model_name='revenda',
            name='bairro',
        ),
        migrations.RemoveField(
            model_name='revenda',
            name='cidade',
        ),
        migrations.RemoveField(
            model_name='revenda',
            name='complemento',
        ),
        migrations.RemoveField(
            model_name='revenda',
            name='documento',
        ),
        migrations.RemoveField(
            model_name='revenda',
            name='dt_abertura',
        ),
        migrations.RemoveField(
            model_name='revenda',
            name='email',
        ),
        migrations.RemoveField(
            model_name='revenda',
            name='endereco',
        ),
        migrations.RemoveField(
            model_name='revenda',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='revenda',
            name='id_clientecob',
        ),
        migrations.RemoveField(
            model_name='revenda',
            name='inscricao_estadual',
        ),
        migrations.RemoveField(
            model_name='revenda',
            name='nome',
        ),
        migrations.RemoveField(
            model_name='revenda',
            name='nome_contato',
        ),
        migrations.RemoveField(
            model_name='revenda',
            name='numero_endereco',
        ),
        migrations.RemoveField(
            model_name='revenda',
            name='score',
        ),
        migrations.RemoveField(
            model_name='revenda',
            name='telefone1',
        ),
        migrations.RemoveField(
            model_name='revenda',
            name='telefone2',
        ),
        migrations.RemoveField(
            model_name='revenda',
            name='total_pedidos',
        ),
        migrations.RemoveField(
            model_name='revenda',
            name='ultimopedido',
        ),
        migrations.AddField(
            model_name='revenda',
            name='cliente',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='connect.cliente'),
        ),
        migrations.AddField(
            model_name='revenda',
            name='nivel',
            field=models.IntegerField(default=1),
        ),
    ]
