# Generated by Django 4.2.2 on 2023-08-03 14:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0065_remove_revenda_cep_remove_revenda_bairro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itens_pedido',
            name='produto_revenda',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='produto_revenda_item', to='connect.produtos_revenda'),
        ),
    ]
