# Generated by Django 4.2.2 on 2023-08-04 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0066_itens_pedido_produto_revenda'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colaborador',
            name='salario',
        ),
        migrations.AddField(
            model_name='colaborador',
            name='numero_endereco',
            field=models.CharField(default=None, max_length=5, null=True),
        ),
    ]
