# Generated by Django 4.2.2 on 2023-08-04 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0067_remove_colaborador_salario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='pagamento_boleto',
            field=models.CharField(default='NAO', max_length=3),
        ),
    ]
