# Generated by Django 4.2.2 on 2023-08-05 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0068_cliente_pagamento_boleto'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos',
            name='informacoes_pagamento',
            field=models.CharField(default=None, max_length=1000, null=True),
        ),
    ]
