# Generated by Django 4.2.2 on 2023-08-06 01:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0069_pedidos_informacoes_pagamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='contas_receber',
            name='cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='connect.cliente'),
        ),
    ]
