# Generated by Django 4.2.2 on 2023-08-06 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0070_contas_receber_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Temp_Pedidos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pedido', models.BigIntegerField(default=None, null=True)),
                ('comissao1', models.FloatField(default=0.0, null=True)),
                ('comissao2', models.FloatField(default=0.0, null=True)),
                ('cliente', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='connect.cliente')),
                ('empresa', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='connect.empresas')),
                ('tipo_pedido', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='connect.tipo_pedido')),
                ('vendedor1', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedido_vendedor1', to='connect.colaborador')),
                ('vendedor2', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedido_vendedor2', to='connect.colaborador')),
            ],
        ),
    ]
