# Generated by Django 4.2.2 on 2023-08-06 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0071_temp_pedidos'),
    ]

    operations = [
        migrations.AddField(
            model_name='temp_pedidos',
            name='total_parcial',
            field=models.FloatField(default=0.0, null=True),
        ),
    ]
