# Generated by Django 4.2.2 on 2023-08-08 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0073_alter_pedidos_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='ponto_referencia',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='pedidos',
            name='ponto_referencia_entrega',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
