# Generated by Django 4.2.2 on 2023-08-09 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0074_cliente_ponto_referencia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itens_pedido',
            name='observacao_item',
            field=models.CharField(default=None, max_length=200, null=True),
        ),
    ]
