# Generated by Django 4.2.2 on 2023-08-09 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0075_itens_pedido_observacao_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos',
            name='retirada_flag',
            field=models.IntegerField(default=0),
        ),
    ]
