# Generated by Django 4.2.2 on 2023-08-09 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0076_pedidos_retirada_flag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Temp_Contas_Receber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pedido', models.IntegerField()),
                ('descricao', models.CharField(max_length=100)),
                ('data_vencimento', models.DateField(default=None, null=True)),
                ('data_pagamento', models.DateField(default=None, null=True)),
                ('tipo_pgto', models.CharField(default='PIX', max_length=50)),
                ('numero_parcela', models.IntegerField()),
                ('total_parcelas', models.IntegerField()),
                ('valor', models.FloatField()),
                ('status_conta', models.CharField(choices=[('Aberto', 'Aberto'), ('Pendente Faturamento', 'Pendente Faturamento'), ('A Vencer', 'A Vencer'), ('Vencida', 'Vencida'), ('Pago', 'Pago')], default='Aberto', max_length=50)),
                ('momento_pagamento', models.CharField(default=None, max_length=100, null=True)),
                ('caminho_boleto', models.CharField(default=None, max_length=100, null=True)),
                ('id_cobranca', models.CharField(default=None, max_length=100, null=True)),
                ('status_cobranca', models.CharField(default=None, max_length=100, null=True)),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='connect.cliente')),
            ],
        ),
    ]
