# Generated by Django 4.2.2 on 2023-08-09 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0077_temp_contas_receber'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos',
            name='borda',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pedidos',
            name='fundo',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pedidos',
            name='letra',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='pedidos',
            name='logomarca',
            field=models.CharField(default='', max_length=255, null=True),
        ),
    ]
