# Generated by Django 4.2.2 on 2023-08-09 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0078_pedidos_borda_pedidos_fundo_pedidos_letra_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos',
            name='valor_acerto',
            field=models.FloatField(default=0.0, null=True),
        ),
    ]
