# Generated by Django 4.2.2 on 2023-08-09 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0079_pedidos_valor_acerto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaborador',
            name='funcao',
            field=models.CharField(choices=[('Gerente', 'Gerente'), ('Administrador', 'Administrador'), ('Vendedor Interno', 'Vendedor Interno'), ('Vendedor Externo', 'Vendedor Externo'), ('Producao', 'Produção'), ('Auxiliar', 'Auxiliar'), ('Logistica', 'Logística'), ('Expedicao', 'Expedicao'), ('Financeiro', 'Financeiro'), ('Recepcionista', 'Recepcionista')], default=' ', max_length=30),
        ),
    ]
