# Generated by Django 4.2.2 on 2023-08-10 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0080_alter_colaborador_funcao'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos',
            name='tipo_entrega',
            field=models.CharField(default='propria', max_length=255, null=True),
        ),
    ]
