# Generated by Django 4.2.2 on 2023-08-10 03:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0081_pedidos_tipo_entrega'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedidos',
            name='tipo_entrega',
        ),
    ]
