# Generated by Django 4.2.2 on 2023-08-10 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0082_remove_pedidos_tipo_entrega'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos',
            name='tipo_entrega',
            field=models.CharField(default=' ', max_length=255, null=True),
        ),
    ]
