# Generated by Django 4.2.2 on 2023-08-10 18:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0084_alter_pedidos_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Numero_Pedidos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.BigIntegerField()),
                ('ultimo_numero', models.BigIntegerField()),
                ('empresa', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='connect.empresas')),
            ],
        ),
    ]
