# Generated by Django 4.2.2 on 2023-08-11 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0086_rename_numero_numero_pedidos_numero_disponivel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos',
            name='datapg_antecipado',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='pedidos',
            name='valor_repasse',
            field=models.FloatField(default=0.0, null=True),
        ),
    ]
