# Generated by Django 4.2.2 on 2023-08-11 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0087_pedidos_datapg_antecipado_pedidos_valor_repasse'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos',
            name='valor_nota',
            field=models.FloatField(default=0.0, null=True),
        ),
    ]
