# Generated by Django 4.2.2 on 2023-08-16 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0088_pedidos_valor_nota'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos',
            name='flag_aberto',
            field=models.IntegerField(default=0),
        ),
    ]
