# Generated by Django 4.2.2 on 2023-08-17 01:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0089_pedidos_flag_aberto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bancos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('agencia', models.CharField(max_length=10)),
                ('numero_conta', models.CharField(max_length=20)),
                ('empresa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='connect.empresas')),
            ],
        ),
    ]
