# Generated by Django 4.2.2 on 2023-08-17 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0090_bancos'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos',
            name='bancopg_antecipado',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
