# Generated by Django 4.2.2 on 2023-08-17 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0091_pedidos_bancopg_antecipado'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos',
            name='bonificado',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bonificados_pedido', to='connect.fornecedor'),
        ),
    ]
