# Generated by Django 4.2.2 on 2023-08-17 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0092_pedidos_bonificado'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos',
            name='flag_nfe_antecipada',
            field=models.IntegerField(default=0),
        ),
    ]
