# Generated by Django 4.2.2 on 2023-08-21 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0094_contas_pagar_banco_contas_pagar_empresa_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos',
            name='vendedor2_comissaov',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='pedidos',
            name='vendedor_comissaov',
            field=models.FloatField(null=True),
        ),
    ]
