# Generated by Django 4.2.2 on 2023-08-23 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0095_pedidos_vendedor2_comissaov_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itens_pedido',
            name='flag_editado',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='itens_pedido',
            name='nome_nf',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='itens_pedido',
            name='preco_nf',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='itens_pedido',
            name='quantidade_nf',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='itens_pedido',
            name='total_item_nf',
            field=models.FloatField(default=0, null=True),
        ),
    ]
