# Generated by Django 4.2.2 on 2023-08-24 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0096_itens_pedido_flag_editado_itens_pedido_nome_nf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos',
            name='status',
            field=models.CharField(choices=[('Aberto', 'Aberto'), ('Produção', 'Produção'), ('Pendente Financeiro', 'Pendente Financeiro'), ('Liberado para Entrega', 'LIBERADO_ENTREGA'), ('Em Rota de Entrega', 'EM_ENTREGA'), ('Finalizado', 'FINALIZADO'), ('Entregue', 'Entregue'), ('Financeiro', 'Financeiro'), ('Faturamento', 'Faturamento'), ('Pendente Logistica', 'Pendente Logistica'), ('Expedição', 'Expedição'), ('Nfe Antecipada', 'Nfe Antecipada'), ('Liberado Coleta', 'Liberado Coleta')], default='Aberto', max_length=50),
        ),
    ]
