# Generated by Django 4.2.2 on 2023-08-25 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0097_alter_pedidos_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos',
            name='status',
            field=models.CharField(choices=[('Aberto', 'Aberto'), ('Produção', 'Produção'), ('Pendente Financeiro', 'Pendente Financeiro'), ('Liberado para Entrega', 'LIBERADO_ENTREGA'), ('Em Rota de Entrega', 'EM_ENTREGA'), ('Finalizado', 'FINALIZADO'), ('Entregue', 'Entregue'), ('Financeiro', 'Financeiro'), ('Faturamento', 'Faturamento'), ('Pendente Logistica', 'Pendente Logistica'), ('Expedição', 'Expedição'), ('Nfe Antecipada', 'Nfe Antecipada'), ('Liberado Coleta', 'Liberado Coleta'), ('Liberado Retirada Cliente', 'Liberado Retirada Cliente')], default='Aberto', max_length=50),
        ),
    ]
