# Generated by Django 4.2.2 on 2023-08-27 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0098_alter_pedidos_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bairro',
            name='regiao',
            field=models.CharField(default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='status',
            field=models.CharField(choices=[('Aberto', 'Aberto'), ('Producao', 'Producao'), ('Pendente Financeiro', 'Pendente Financeiro'), ('Liberado para Entrega', 'LIBERADO_ENTREGA'), ('Em Rota de Entrega', 'EM_ENTREGA'), ('Finalizado', 'FINALIZADO'), ('Entregue', 'Entregue'), ('Financeiro', 'Financeiro'), ('Faturamento', 'Faturamento'), ('Pendente Logistica', 'Pendente Logistica'), ('Expedicao', 'Expedicao'), ('Nfe Antecipada', 'Nfe Antecipada'), ('Liberado Coleta', 'Liberado Coleta'), ('Liberado Retirada Cliente', 'Liberado Retirada Cliente')], default='Aberto', max_length=50),
        ),
        migrations.CreateModel(
            name='Rota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regiao', models.CharField(max_length=255)),
                ('pedido', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='connect.pedidos')),
            ],
        ),
    ]
