# Generated by Django 4.2.2 on 2023-08-28 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0099_bairro_regiao_alter_pedidos_status_rota'),
    ]

    operations = [
        migrations.AddField(
            model_name='itens_pedido',
            name='adicional',
            field=models.FloatField(default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='itens_pedido',
            name='frete_embutido',
            field=models.FloatField(default=0.0, null=True),
        ),
    ]
