# Generated by Django 4.2.2 on 2023-09-10 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0100_itens_pedido_adicional_itens_pedido_frete_embutido'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reparos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacao', models.CharField(max_length=255)),
                ('pedido', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='connect.pedidos')),
            ],
        ),
    ]
