# Generated by Django 4.2.2 on 2023-09-11 01:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0101_reparos'),
    ]

    operations = [
        migrations.AddField(
            model_name='reparos',
            name='data_coleta',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='reparos',
            name='usuario_coleta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='connect.colaborador'),
        ),
    ]
