# Generated by Django 4.2.2 on 2023-09-12 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0102_reparos_data_coleta_reparos_usuario_coleta'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos',
            name='dataEmissao_nfe',
            field=models.DateField(default=None, null=True),
        ),
    ]
