# Generated by Django 4.2.2 on 2023-09-15 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0103_pedidos_dataemissao_nfe'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos',
            name='flag_impressao',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name='pedidos',
            name='status',
            field=models.CharField(choices=[('Aberto', 'Aberto'), ('Confirma os Valores', 'Confirma os Valores'), ('duplicado', 'duplicado'), ('Producao', 'Producao'), ('Pendente Financeiro', 'Pendente Financeiro'), ('Liberado para Entrega', 'LIBERADO_ENTREGA'), ('Em Rota de Entrega', 'EM_ENTREGA'), ('Finalizado', 'FINALIZADO'), ('Entregue', 'Entregue'), ('Financeiro', 'Financeiro'), ('Faturamento', 'Faturamento'), ('Pendente Logistica', 'Pendente Logistica'), ('Expedicao', 'Expedicao'), ('Nfe Antecipada', 'Nfe Antecipada'), ('Liberado Coleta', 'Liberado Coleta'), ('Liberado Retirada Cliente', 'Liberado Retirada Cliente')], default='Aberto', max_length=50),
        ),
    ]
