# Generated by Django 4.2.2 on 2023-10-02 02:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0104_pedidos_flag_impressao_alter_pedidos_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='atendimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone', models.CharField(max_length=13)),
                ('data', models.DateField()),
                ('tempo', models.DateTimeField()),
                ('status', models.CharField(default='Aberto', max_length=100)),
                ('ultima_opcao', models.IntegerField(null=True)),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='connect.cliente')),
            ],
        ),
    ]
