# Generated by Django 4.2.2 on 2023-10-04 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0105_atendimento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cob_Unificada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='connect.cliente')),
                ('conta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='connect.contas_receber')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='connect.pedidos')),
            ],
        ),
    ]
