# Generated by Django 4.2.2 on 2023-10-10 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0106_cob_unificada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cob_unificada',
            name='cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='connect.cliente'),
        ),
        migrations.AlterField(
            model_name='cob_unificada',
            name='conta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='connect.contas_receber'),
        ),
        migrations.AlterField(
            model_name='cob_unificada',
            name='pedido',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='connect.pedidos'),
        ),
    ]
