# Generated by Django 4.2.2 on 2023-10-11 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0107_alter_cob_unificada_cliente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contas_receber',
            name='flag_uni',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
