# Generated by Django 4.2.2 on 2023-10-17 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0108_contas_receber_flag_uni'),
    ]

    operations = [
        migrations.AddField(
            model_name='temp_contas_receber',
            name='flag_uni',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
