# Generated by Django 4.1.7 on 2024-02-26 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0109_temp_contas_receber_flag_uni'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos',
            name='flag_entrega_rejeitada',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='pedidos',
            name='observacao_entrega_rejeitada',
            field=models.CharField(default=' ', max_length=255, null=True),
        ),
    ]
