# Generated by Django 4.1.7 on 2024-02-26 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0110_pedidos_flag_entrega_rejeitada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registra',
            name='data_rejeicao',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='registra',
            name='observacao_rejeicao',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='registra',
            name='data_entrega',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
