# Generated by Django 4.1.7 on 2024-02-26 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0111_registra_data_rejeicao_registra_observacao_rejeicao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtos_revenda',
            name='preco_base_4',
            field=models.FloatField(default=None),
        ),
    ]
