# Generated by Django 4.1.7 on 2024-07-30 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0113_pedidos_comprador_email_pedidos_comprador_nome_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inadimplencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.CharField(max_length=12, null=True)),
                ('flag', models.IntegerField(default=None, null=True)),
            ],
        ),
    ]
