# Generated by Django 4.1.7 on 2024-07-31 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0114_inadimplencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrosLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField()),
                ('operacao', models.CharField(max_length=300, null=True)),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='connect.colaborador')),
                ('conta', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='connect.contas_receber')),
                ('pedido', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='connect.pedidos')),
            ],
        ),
    ]
