# Generated by Django 4.1.7 on 2024-09-02 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0115_registroslog'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresas',
            name='token_nota',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='empresas',
            name='url_nota',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
