# Generated by Django 4.1.7 on 2024-09-19 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0116_empresas_token_nota_empresas_url_nota'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status_Colaborador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='colaborador',
            name='data_admissao',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='data_desligamento',
            field=models.DateField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='status',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='connect.status_colaborador'),
        ),
    ]
