# Generated by Django 4.1.7 on 2024-10-06 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0118_motivos_desligamento_colaborador_motivo_desligamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusOr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TipoMedida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='pedidos',
            name='flag_notificacao',
            field=models.IntegerField(default=1),
        ),
        migrations.CreateModel(
            name='Orcamentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.BigIntegerField()),
                ('datacriacao', models.DateField()),
                ('dataexpiracao', models.DateField(default=None, null=True)),
                ('data_ultima_atualizacao', models.DateField(default=None, null=True)),
                ('validade', models.IntegerField()),
                ('valor_total', models.FloatField(default=0.0)),
                ('caminho1', models.CharField(default=None, max_length=255, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='connect.cliente')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='connect.empresas')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='connect.statusor')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='connect.colaborador')),
            ],
        ),
        migrations.CreateModel(
            name='Orcamento_Comentarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('orcamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='connect.orcamentos')),
            ],
        ),
        migrations.CreateModel(
            name='ItensOrcamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
                ('quantidade', models.IntegerField()),
                ('comprimento', models.FloatField()),
                ('largura', models.FloatField()),
                ('valor_item', models.FloatField()),
                ('valor_total_item', models.FloatField(default=0.0, null=True)),
                ('codigo_orcamento', models.BigIntegerField()),
                ('orcamento', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='connect.orcamentos')),
                ('tipo_medida', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='connect.tipomedida')),
            ],
        ),
    ]
