# Generated by Django 4.1.7 on 2024-10-20 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0120_orcamento_comentarios_colaborador_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpcoesFornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TemplateFornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(default=None, max_length=255, null=True)),
                ('caminho_imagem', models.CharField(default=None, max_length=255, null=True)),
                ('fornecedor', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='connect.opcoesfornecedor')),
            ],
        ),
    ]
