# Generated by Django 4.1.7 on 2024-10-20 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0121_opcoesfornecedor_templatefornecedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='itensorcamento',
            name='template',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='connect.templatefornecedor'),
        ),
    ]
