# Generated by Django 4.1.7 on 2024-10-20 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0122_itensorcamento_template'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itensorcamento',
            name='template',
        ),
        migrations.AddField(
            model_name='orcamentos',
            name='template',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='connect.templatefornecedor'),
        ),
    ]
