# Generated by Django 4.1.7 on 2024-10-20 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0123_remove_itensorcamento_template_orcamentos_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaborador',
            name='caminho_foto',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
