# Generated by Django 4.1.7 on 2024-10-23 22:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0124_colaborador_caminho_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipo_Indicacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(default=None, max_length=255, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='cliente',
            name='tipo_entrada',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='connect.tipo_indicacao'),
        ),
    ]
