# Generated by Django 4.1.7 on 2024-10-28 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0125_tipo_indicacao_cliente_tipo_entrada'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamentos',
            name='email_cliente',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='orcamentos',
            name='nome_cliente',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='orcamentos',
            name='telefone_cliente',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
