# Generated by Django 4.1.7 on 2024-10-28 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0126_orcamentos_email_cliente_orcamentos_nome_cliente_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('telefone', models.CharField(max_length=20)),
                ('documento', models.CharField(default=None, max_length=255, null=True)),
                ('email', models.CharField(default=None, max_length=255, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='orcamentos',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='orcamentos',
            name='email_cliente',
        ),
        migrations.RemoveField(
            model_name='orcamentos',
            name='nome_cliente',
        ),
        migrations.RemoveField(
            model_name='orcamentos',
            name='telefone_cliente',
        ),
        migrations.AddField(
            model_name='orcamentos',
            name='cliente_lead',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='connect.leads'),
        ),
    ]
