# Generated by Django 4.1.7 on 2024-10-29 23:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0127_leads_remove_orcamentos_cliente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='templatefornecedor',
            name='empresa',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='connect.empresas'),
        ),
    ]
