# Generated by Django 4.1.7 on 2024-10-30 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0128_templatefornecedor_empresa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Status_Reparo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='reparos',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='connect.itens_pedido'),
        ),
        migrations.CreateModel(
            name='Guia_Reparo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.BigIntegerField()),
                ('observacao', models.CharField(default=None, max_length=255, null=True)),
                ('data_criacao', models.DateField()),
                ('data_alteracao', models.DateField()),
                ('pedido', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='connect.pedidos')),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='connect.status_reparo')),
            ],
        ),
        migrations.AddField(
            model_name='reparos',
            name='guia',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, to='connect.guia_reparo'),
        ),
    ]
