# Generated by Django 4.1.7 on 2024-11-02 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0129_status_reparo_reparos_item_guia_reparo_reparos_guia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guia_reparo',
            name='observacao',
            field=models.TextField(default=None, null=True),
        ),
    ]
