# Generated by Django 4.1.7 on 2024-11-02 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0130_alter_guia_reparo_observacao'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos',
            name='flag_reparo',
            field=models.IntegerField(default=0),
        ),
    ]
