# Generated by Django 4.1.7 on 2024-11-02 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0131_pedidos_flag_reparo'),
    ]

    operations = [
        migrations.AddField(
            model_name='guia_reparo',
            name='data_coleta',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='guia_reparo',
            name='data_entrega',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='guia_reparo',
            name='usuario_coleta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='connect.colaborador'),
        ),
        migrations.AddField(
            model_name='guia_reparo',
            name='usuario_entrega',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuario_entrega', to='connect.colaborador'),
        ),
    ]
