# Generated by Django 4.1.7 on 2024-11-02 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0132_guia_reparo_data_coleta_guia_reparo_data_entrega_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orcamentos_Templates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orcamento', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='connect.orcamentos')),
                ('templates', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='connect.templatefornecedor')),
            ],
        ),
    ]
