# Generated by Django 4.1.7 on 2024-11-02 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0133_orcamentos_templates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orcamentos',
            name='template',
        ),
    ]
