# Generated by Django 4.1.7 on 2024-11-02 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0134_remove_orcamentos_template'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orcamentos_templates',
            old_name='templates',
            new_name='template',
        ),
    ]
