# Generated by Django 4.1.7 on 2024-11-04 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0135_rename_templates_orcamentos_templates_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamentos',
            name='forma_pagamento',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
