# Generated by Django 4.1.7 on 2024-11-07 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0136_orcamentos_forma_pagamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamentos',
            name='valor_com_desconto',
            field=models.FloatField(default=0.0),
        ),
    ]
