# Generated by Django 4.1.7 on 2024-11-07 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0137_orcamentos_valor_com_desconto'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamentos',
            name='texto_garantia',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
