# Generated by Django 4.1.7 on 2024-11-07 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0138_orcamentos_texto_garantia'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamentos',
            name='flag_carimbo',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
