# Generated by Django 4.1.7 on 2024-11-07 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0139_orcamentos_flag_carimbo'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresas',
            name='caminho_carimbo',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
