# Generated by Django 4.1.7 on 2024-11-07 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0140_empresas_caminho_carimbo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresas',
            name='caminho_carimbo',
        ),
    ]
