# Generated by Django 4.1.7 on 2024-11-07 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0141_remove_empresas_caminho_carimbo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Condicoes_Pagamentos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
            ],
        ),
    ]
