# Generated by Django 4.1.7 on 2024-11-07 23:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0142_condicoes_pagamentos'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos',
            name='condicao_pagamento',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='connect.condicoes_pagamentos'),
        ),
    ]
