# Generated by Django 4.1.7 on 2024-11-07 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0143_pedidos_condicao_pagamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='condicoes_pagamentos',
            name='quantidades_parcelas',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
