# Generated by Django 4.1.7 on 2024-11-18 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0144_condicoes_pagamentos_quantidades_parcelas'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtos',
            name='flag_conferir',
            field=models.IntegerField(default=0),
        ),
    ]
