# Generated by Django 4.1.7 on 2024-11-26 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0146_produtos_revenda_flag_conferir'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='flag',
            field=models.IntegerField(default=0),
        ),
    ]
