# Generated by Django 4.1.7 on 2024-11-27 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0147_cliente_flag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos',
            name='status',
            field=models.CharField(choices=[('Aberto', 'Aberto'), ('Confirma os Valores', 'Confirma os Valores'), ('duplicado', 'duplicado'), ('Producao', 'Producao'), ('Pendente Financeiro', 'Pendente Financeiro'), ('Liberado para Entrega', 'LIBERADO_ENTREGA'), ('Em Rota de Entrega', 'EM_ENTREGA'), ('Finalizado', 'FINALIZADO'), ('Entregue', 'Entregue'), ('Financeiro', 'Financeiro'), ('Faturamento', 'Faturamento'), ('Pendente Logistica', 'Pendente Logistica'), ('Expedicao', 'Expedicao'), ('Nfe Antecipada', 'Nfe Antecipada'), ('Liberado Coleta', 'Liberado Coleta'), ('Liberado Retirada Cliente', 'Liberado Retirada Cliente'), ('Liberado Retirada Cliente', 'Conferir Item')], default='Aberto', max_length=50),
        ),
    ]
