# Generated by Django 4.1.7 on 2024-11-29 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0149_alter_pedidos_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='itens_pedido',
            name='pedido_itens',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='connect.pedidos'),
        ),
    ]
