# Generated by Django 4.1.7 on 2024-11-29 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0150_itens_pedido_pedido_itens'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtos',
            name='modelo',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='produtos_revenda',
            name='modelo',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
