# Generated by Django 4.1.7 on 2024-12-06 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0151_produtos_modelo_produtos_revenda_modelo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='data_cadastro',
            field=models.DateField(default=None, null=True),
        ),
    ]
