# Generated by Django 4.1.7 on 2024-12-18 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0152_cliente_data_cadastro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroslog',
            name='pedido',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='connect.pedidos'),
        ),
    ]
