# Generated by Django 4.1.7 on 2025-02-10 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0153_alter_registroslog_pedido'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaborador',
            name='telefone_comercial',
            field=models.CharField(default=None, max_length=15, null=True),
        ),
    ]
