# Generated by Django 4.1.7 on 2025-03-24 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0155_empresas_flag_pagamento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contas_pagar',
            name='status',
            field=models.CharField(choices=[('Aberto', 'Aberto'), ('A Vencer', 'A Vencer'), ('Vencida', 'Vencida'), ('Pago', 'Pago'), ('Aguardando', 'Aguardando')], default='Aberto', max_length=50),
        ),
    ]
