# Generated by Django 4.1.7 on 2025-05-09 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0156_alter_contas_pagar_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orcamentos',
            name='bairro_entrega',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='orcamentos',
            name='cidade_entrega',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='orcamentos',
            name='endereco_entrega',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='orcamentos',
            name='estado_entrega',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
