# Generated by Django 4.1.7 on 2025-05-20 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0157_orcamentos_bairro_entrega_orcamentos_cidade_entrega_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaborador',
            name='endereco',
            field=models.CharField(max_length=255),
        ),
    ]
