# Generated by Django 4.1.7 on 2025-06-10 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0158_alter_colaborador_endereco'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresas',
            name='aws_chave',
            field=models.CharField(default='0', max_length=255),
            preserve_default=False,
        ),
    ]
