# Generated by Django 4.1.7 on 2025-06-10 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0159_empresas_aws_chave'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresas',
            name='aws_id',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='empresas',
            name='aws_chave',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
